// import type { Metadata } from "next";
"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [expanded, setExpanded] = useState(true);
  return (
    <html lang="en">
      <body className={expanded ? "sb-expanded" : ""}>
        <aside>
          <nav>
            <ul>
              <p>MagisPlan</p>
              <li>
                <a onClick={() => setExpanded(!expanded)}>
                  <span>Collapse</span>
                </a>
              </li>
              <li>
                <a href="#">
                  <i></i>
                  <span>Home</span>
                </a>
              </li>
              <li>
                <a href="#">
                  <i></i>
                  <span>Chat</span>
                </a>
              </li>
              <li>
                <a href="#">
                  <i></i>
                  <span>Profile</span>
                </a>
              </li>
              <li>
                <a href="#">
                  <i></i>
                  <span>My Projects</span>
                </a>
              </li>
            </ul>
          </nav>
        </aside>
        <main  className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {children}
        </main>
      </body>
    </html>
  );
}
